id: I0EF13371
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:28:54.401797
last_modified: 2023-01-04 11:28:54.401812
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  '1379':
    title: Prayer for the Long Life of Alak Zenkar Rinpoche
    base_file: 1379.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
